### ISSUE TITLE
Configurate Integration

### ISSUE THREAD

**Issue by ghost** [tr7zw/Item-NBT-API#181]
I think it might be good idea to integrate this lib with configurate project. Configurate is an open-source configuration library developed by Sponge team. Some good bukkit-based engines like Paper is already using configurate. In my opinion it may replace the old bukkit configuration system. Link to the project: https://github.com/SpongePowered/Configurate. 

The nbt structure could be converted into a configurate node and vice versa. It would create an opportunity for powerful NBT-based serializers for entities/block/item data. For example: 

Let's take a hoe with unbreaking III:

Bukkit representation:

```
==: org.bukkit.inventory.ItemStack
  type: STONE_HOE
  amount: 1
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    enchants:
      DURABILITY: 3
```

It is not very intuitive, because end users are more sticked to minecraft naming, not bukkit naming.

NBT String representation

```
item: '{Count:1b,id:"minecraft:stone_hoe",tag:{Enchantments:[{id:"minecraft:unbreaking",lvl:3s}]}}'
```

It is intuitive, because it uses nbt and minecraft naming, but passing everything as nbt string in yaml file is half-soltion.

NBT converted to configurate node:

```
item:
  Count: 1
  id: "minecraft:stone_hoe"
  tag:
    Enchantments:
    -
      id: "minecraft:unbreaking"
      lvl: 3
```

And with help of Configurate's Object Mapper this complexity can be acomplished with simple:

```java
@ConfigSerializable
public class Config {
  
  private ItemStack item = Items.DEFAULT_ITEM;

}

at the developer site.

Configurate is very powerfull. The only thing to implement is the way to change a NBTCompount into ConfigurationNode and node to compund. It has not to be a major funcionality, but only a minor feature. The next step is to add some usefull serializers for think like ItemStack in the example.
